name: Manual Test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: true
        default: ''
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize ]

env:
  BRANCH: ${{ github.event.inputs.branch }}

jobs:
  Build-Deploy-Backend:
    runs-on: ubuntu-latest
    steps:
      - name: Test 1
        if: env.BRANCH == ''
        run: |
          echo "${GITHUB_HEAD_REF}"
          export BRANCH="${GITHUB_HEAD_REF}"
          echo "$BRANCH"
      - name: Test 2
        if: env.BRANCH != ''
        run: |
          echo "$BRANCH"
      - name: Test 3
        run: |
          echo "$BRANCH"
